# Generated by Django 5.2.3 on 2025-08-03 18:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('alert_type', models.CharField(choices=[('rate_limit', 'Rate Limit Exceeded'), ('malicious_content', 'Malicious Content Detected'), ('spam', 'Spam Attempt'), ('suspicious_activity', 'Suspicious Activity')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True)),
                ('blocked_content', models.TextField(blank=True)),
                ('severity', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('session_key', models.CharField(max_length=40)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('total_duration', models.DurationField(default=datetime.timedelta)),
                ('page_views', models.IntegerField(default=0)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'unique_together': {('ip_address', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='ServiceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('caesar', 'Caesar Cipher'), ('vigenere', 'Vigenère Cipher'), ('hill', 'Hill Cipher'), ('playfair', 'Playfair Cipher'), ('aes', 'AES Encryption'), ('des', 'DES Encryption'), ('rsa', 'RSA Encryption'), ('md5', 'MD5 Hash'), ('sha256', 'SHA-256 Hash'), ('sha512', 'SHA-512 Hash'), ('hmac', 'HMAC'), ('diffie_hellman', 'Diffie-Hellman Key Exchange'), ('chatbot', 'AI Chatbot')], max_length=50)),
                ('usage_time', models.DateTimeField(auto_now_add=True)),
                ('input_data', models.TextField(blank=True)),
                ('output_data', models.TextField(blank=True)),
                ('operation', models.CharField(blank=True, max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='ChatBot.visitorsession')),
            ],
            options={
                'ordering': ['-usage_time'],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField()),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='ChatBot.visitorsession')),
            ],
            options={
                'ordering': ['-visit_time'],
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_hash', models.CharField(max_length=32)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='ChatBot.visitorsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
